version: "3.9"

services:
  rocktouchbot:
    build: .
    container_name: rocktouchbot
    restart: unless-stopped

    env_file:
      - ./data/rocktouch/.env

    volumes:
      - ./data/rocktouch/:/app/data

    command: python bot.py

  childrengroup:
    build: .
    container_name: childrengroup
    restart: unless-stopped

    env_file:
      - ./data/childrengroup/.env

    volumes:
      - ./data/childrengroup/:/app/data

    command: python bot.py
